/**
 * Development helper: inserts many sample tasks to test performance.
 *
 * Usage:  npm run seed            (10,000 tasks)
 *         npm run seed -- 50000   (custom count)
 *
 * Start the app at least once first so the schema exists (migrations run on
 * app startup). All rows are inserted in a single transaction: either every
 * row is written or none are.
 */
import path from "node:path";
import Database from "better-sqlite3";
import nextEnv from "@next/env";

// Load .env / .env.local the same way Next.js does, so DATABASE_PATH matches the app.
nextEnv.loadEnvConfig(process.cwd());

const count = Number.parseInt(process.argv[2] ?? "10000", 10);
if (!Number.isInteger(count) || count <= 0) {
  console.error("Count must be a positive integer.");
  process.exit(1);
}

const dbPath = process.env.DATABASE_PATH || path.join(process.cwd(), "data", "tasks.db");
const db = new Database(dbPath, { fileMustExist: true });
db.pragma("journal_mode = WAL");
db.pragma("busy_timeout = 5000");

const hasTasksTable = db
  .prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'tasks'")
  .get();
if (!hasTasksTable) {
  console.error("The tasks table doesn't exist yet. Start the app once (npm run dev), then re-run.");
  process.exit(1);
}

const verbs = ["Buy", "Call", "Write", "Review", "Plan", "Fix", "Read", "Clean", "Email", "Book"];
const things = ["groceries", "the report", "mum", "the dentist", "slides", "the bike", "a book", "the garage", "taxes", "tickets"];

const insert = db.prepare("INSERT INTO tasks (title, description) VALUES (?, ?)");
const insertMany = db.transaction((n) => {
  for (let i = 1; i <= n; i++) {
    const title = `${verbs[i % verbs.length]} ${things[(i * 7) % things.length]} #${i}`;
    const description = `Sample task ${i}. Generated by the seed script for performance testing.`;
    insert.run(title, description);
  }
});

const started = performance.now();
insertMany(count);
const total = db.prepare("SELECT COUNT(*) AS total FROM tasks").get().total;
db.close();

console.log(
  `Inserted ${count} tasks in ${Math.round(performance.now() - started)} ms (total now ${total}).`,
);
